spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: document-resource-service
          uri: http://localhost:9191
          predicates:
            - Path=/document/**
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8080/auth/realms/interno-realm
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            client-id: spring-gateway-client
            client-secret: 95d6a850-0562-41cc-ab4a-c875029857bc
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
server:
  port: 9090

